"""
Aggregate every reports/<step>/metrics.json + summary.md into a single
FINAL_REPORT.md (and JSON sidecar) at reports/FINAL_REPORT.md.

Discovers steps dynamically — drop a new evaluator that writes
`metrics.json` + `summary.md` under reports/<name>/ and it lands here
automatically.

Run:
    python aggregate_reports.py --reports-dir reports --out reports/FINAL_REPORT.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import mlflow_utils as mlu


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--reports-dir", default="reports")
    p.add_argument("--out", default="reports/FINAL_REPORT.md")
    return p.parse_args()


def main():
    args = parse_args()
    root = Path(args.reports_dir)
    if not root.exists():
        print(f"[aggregate] no reports/ dir at {root}; nothing to do")
        return
    steps = sorted([d for d in root.iterdir() if d.is_dir()])

    bundle = {}
    md = ["# Face Recognition — Final AI evaluation report\n\n",
          "This file is auto-generated by `aggregate_reports.py` from every "
          "evaluator under `reports/`. Each step's full numbers live in its "
          "own JSON; this is the executive summary.\n\n",
          "## Table of contents\n"]
    for d in steps:
        md.append(f"- [{d.name}](#{d.name.replace('_','-')})\n")
    md.append("\n")

    for d in steps:
        md.append(f"## {d.name}\n\n")
        summary = d / "summary.md"
        metrics = d / "metrics.json"
        if summary.exists():
            md.append(summary.read_text())
            md.append("\n")
        else:
            md.append("(no summary.md)\n")
        if metrics.exists():
            try:
                bundle[d.name] = json.loads(metrics.read_text())
            except Exception:
                bundle[d.name] = {"_error": "could not parse metrics.json"}
        # Inline any plots in the same dir.
        plots = sorted(list(d.glob("*.png")))
        if plots:
            md.append("\n### Plots\n")
            for png in plots:
                rel = png.relative_to(root.parent)
                md.append(f"![{png.stem}]({rel})\n")
            md.append("\n")
        md.append("---\n\n")

    Path(args.out).write_text("".join(md))
    Path(args.out).with_suffix(".json").write_text(json.dumps(bundle, indent=2))
    print(f"[aggregate] wrote {args.out} and {Path(args.out).with_suffix('.json')}")

    # MLflow: one umbrella run that stores the FINAL_REPORT so reviewers can
    # see the whole project state from a single MLflow page.
    with mlu.init_run(
        experiment="aggregate_reports",
        run_name="aggregate_final_report",
        category="Reporting",
        tags={"step": "aggregate_reports"},
    ):
        mlu.log_artifact_file(args.out, artifact_path="final")
        mlu.log_artifact_file(Path(args.out).with_suffix(".json"),
                              artifact_path="final")


if __name__ == "__main__":
    main()
